### PR TITLE
add notable contribution for @jaekwon

### PR DESCRIPTION
**Pull request by moul**
Author: @jaekwon
Commit: https://github.com/gnolang/gno/commit/6ff6762d663bc577531c44e259a1ffa132b49b44

### CODE REVIEW

**Comment by moul** [comment]
Seeking co-endorsers. Thank you.

**Review by MichaelFrazzy — APPROVED** [review]

**Review by thehowl — APPROVED** [review]
a good start :)

**Review by leohhhn — APPROVED** [review]
LGTM! :)

**Comment by albttx** [comment]
Love it!

**Review by albttx — APPROVED** [review]

**Pull request merged**
